version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - OPENAI_API_URL=https://api.openai.com/v1/chat/completions
      - OPENAI_API_KEY=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
      - GITHUB_TOKEN=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
      - FLASK_SECRET_KEY=your-secret-key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 3
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: